// Reference process library (editorial, textbook-level definitions).
// These records describe generic manufacturing steps. They carry no claims about any company;
// company/equipment links are derived at build time from source-backed equipment mappings.
// eq: taxonomy codes (prefix match: "A01" covers A01.xx). tech/mat: slugs from technologies.mjs / materials.mjs.
// flow: position in the main process-flow diagram (null = not on the main flow).

export const STAGES = [
  { id: "WM", name: "Wafer manufacturing", note: "Substrate production before device processing" },
  { id: "FE", name: "Front-end (wafer processing)", note: "Device and interconnect fabrication on the wafer" },
  { id: "TS", name: "Wafer test", note: "Electrical test at wafer level" },
  { id: "BE", name: "Back-end (assembly & packaging)", note: "Singulation, assembly, encapsulation and final test" },
  { id: "AP", name: "Advanced packaging", note: "Heterogeneous integration, wafer- and panel-level packaging" },
  { id: "DS", name: "Display & MicroLED", note: "Panel and MicroLED processing that shares laser/thin-film tools" },
  { id: "FA", name: "Fab infrastructure & subfab", note: "Automation, vacuum, abatement, utilities supporting the tools" },
];

const P = (slug, stage, name, o) => ({ slug, stage, name, ...o });

export const PROCESSES = [
  // ---------- Wafer manufacturing ----------
  P("crystal-growth", "WM", "Crystal growth", { flow: 1, legacy_ps: ["PS01"], eq: ["K01"], mat: ["silicon", "sic", "gan", "gaas", "inp", "sapphire"],
    description: "Growth of a single-crystal boule from melt or vapour (e.g. Czochralski or float-zone for silicon, physical vapour transport for SiC).",
    purpose: "Produce defect-controlled single-crystal material of the required orientation, doping and diameter.",
    inputs: ["High-purity polysilicon or source material", "Seed crystal", "Dopants"], outputs: ["Single-crystal ingot / boule"],
    parameters: ["Pull rate", "Rotation rate", "Melt / growth temperature", "Ambient gas"], quality: ["Dislocation density", "Resistivity uniformity", "Oxygen / carbon content"],
    defects: ["Dislocations", "Micropipes (SiC)", "Crystal-originated particles"] }),
  P("ingot-shaping", "WM", "Ingot grinding & shaping", { legacy_ps: ["PS01"], eq: ["K02"], mat: ["silicon", "sic"],
    description: "Cropping, cylindrical grinding and notch/flat forming of the as-grown ingot.", purpose: "Bring the ingot to final diameter and mark crystal orientation.",
    inputs: ["As-grown ingot"], outputs: ["Shaped ingot"], parameters: ["Diameter tolerance", "Notch/flat geometry"], quality: ["Diameter", "Orientation accuracy"], defects: ["Edge chipping"] }),
  P("wafer-slicing", "WM", "Wafer slicing (wire sawing)", { flow: 2, legacy_ps: ["PS01"], eq: ["K03", "K04", "F01"], tech: ["wire-sawing", "laser-cutting"], mat: ["silicon", "sic"],
    description: "Separation of the ingot into wafers, usually by multi-wire sawing; laser-based separation is also used for hard materials such as SiC.",
    purpose: "Convert the ingot into wafers with minimum kerf loss and subsurface damage.", inputs: ["Shaped ingot", "Wire / slurry or diamond wire"], outputs: ["As-cut wafers"],
    parameters: ["Wire speed", "Feed rate", "Kerf width"], quality: ["Total thickness variation (TTV)", "Warp / bow", "Kerf loss"], defects: ["Saw marks", "Subsurface damage", "Breakage"] }),
  P("lapping", "WM", "Lapping", { legacy_ps: ["PS01"], eq: ["K05"], mat: ["silicon", "sic"], description: "Abrasive planarisation of both wafer faces after slicing.",
    purpose: "Remove saw damage and establish flatness and parallelism.", inputs: ["As-cut wafers", "Abrasive slurry"], outputs: ["Lapped wafers"], parameters: ["Removal rate", "Pressure"], quality: ["TTV", "Flatness"], defects: ["Scratches", "Residual damage"] }),
  P("wafer-grinding", "WM", "Wafer surface & edge grinding", { legacy_ps: ["PS01"], eq: ["K06"], mat: ["silicon", "sic"], description: "Grinding of wafer faces and edge profiling.",
    purpose: "Achieve thickness targets and a robust edge profile.", inputs: ["Lapped or as-cut wafers"], outputs: ["Ground wafers"], parameters: ["Grit size", "Spindle speed"], quality: ["Thickness", "Edge profile"], defects: ["Edge chips", "Grinding marks"] }),
  P("wafer-polishing", "WM", "Wafer polishing", { flow: 3, legacy_ps: ["PS01"], eq: ["K07", "C05"], mat: ["silicon", "sic", "cmp-slurry", "cmp-pad"],
    description: "Chemical-mechanical polishing of the bare wafer (often double-side) to a mirror finish.", purpose: "Deliver the flatness and surface roughness required for device processing.",
    inputs: ["Ground wafers", "Slurry", "Polishing pads"], outputs: ["Prime polished wafers"], parameters: ["Down force", "Platen speed", "Slurry flow"], quality: ["Site flatness", "Surface roughness", "Nanotopography"], defects: ["Scratches", "Haze", "Slurry residue"] }),
  P("wafer-cleaning-bare", "WM", "Final wafer cleaning", { legacy_ps: ["PS07"], eq: ["K08"], mat: ["ultrapure-water", "acids", "bases"], description: "Wet cleaning of polished wafers before packing.",
    purpose: "Remove particles, metals and organics from prime wafers.", inputs: ["Polished wafers", "Cleaning chemistries", "UPW"], outputs: ["Clean prime wafers"], parameters: ["Chemistry concentration", "Temperature"], quality: ["Particle count", "Metal contamination"], defects: ["Particles", "Watermarks"] }),
  P("bare-wafer-inspection", "WM", "Bare-wafer inspection", { legacy_ps: ["PS09", "PS08"], eq: ["K09", "A30"], description: "Inspection and geometry measurement of incoming or outgoing bare wafers.",
    purpose: "Qualify wafer geometry and surface defectivity.", inputs: ["Bare wafers"], outputs: ["Inspection / geometry data"], parameters: ["Sensitivity", "Throughput"], quality: ["Defect capture rate"], defects: ["Particles", "Pits", "Slip lines"] }),
  P("epitaxy", "WM", "Epitaxy", { flow: 4, legacy_ps: ["PS01"], eq: ["A09.10", "A09.11", "F03", "G"], tech: ["epitaxy", "mocvd", "mbe"], mat: ["silicon", "sic", "gan", "gaas", "inp", "precursor-gases"],
    description: "Growth of a single-crystal film on a single-crystal substrate, e.g. Si or SiC homo-epitaxy, or GaN/GaAs/InP compound layers by MOCVD or MBE.",
    purpose: "Create layers with controlled doping, composition and thickness that the substrate alone cannot provide.", inputs: ["Substrate wafer", "Precursor gases", "Carrier gases"], outputs: ["Epitaxial wafer"],
    parameters: ["Growth temperature", "Pressure", "Precursor ratios"], quality: ["Thickness & doping uniformity", "Defect density"], defects: ["Stacking faults", "Basal plane dislocations (SiC)", "Particles"] }),

  // ---------- Front-end ----------
  P("wafer-clean", "FE", "Wafer cleaning", { flow: 5, legacy_ps: ["PS07"], eq: ["A04", "A05", "A06", "A07", "A20"], tech: ["wet-processing"], mat: ["ultrapure-water", "acids", "bases", "solvents"],
    description: "Removal of particles, organic and metallic contaminants and native oxide, by wet (batch or single-wafer) or dry/plasma methods. Repeated many times in the flow.",
    purpose: "Keep surfaces free of contaminants that cause yield loss.", inputs: ["Wafers", "Cleaning chemistries", "UPW"], outputs: ["Clean wafers"], parameters: ["Chemistry", "Temperature", "Megasonic power"], quality: ["Particle adders", "Metal contamination"], defects: ["Particles", "Pattern collapse", "Watermarks"] }),
  P("oxidation", "FE", "Oxidation", { flow: 6, legacy_ps: ["PSX1"], eq: ["A16", "A11"], tech: ["furnace-thermal"], mat: ["oxygen", "hydrogen", "nitrogen"],
    description: "Thermal growth of silicon dioxide by exposing silicon to oxygen or steam at high temperature.", purpose: "Form gate, field or masking oxides.",
    inputs: ["Wafers", "O₂ / H₂O"], outputs: ["Oxidised wafers"], parameters: ["Temperature", "Time", "Ambient"], quality: ["Oxide thickness uniformity"], defects: ["Pinholes", "Interface traps"] }),
  P("diffusion", "FE", "Diffusion", { legacy_ps: ["PSX1"], eq: ["A11"], tech: ["furnace-thermal"], description: "High-temperature redistribution of dopants in a furnace.",
    purpose: "Form junctions and wells.", inputs: ["Doped wafers"], outputs: ["Diffused junctions"], parameters: ["Temperature", "Time"], quality: ["Sheet resistance", "Junction depth"], defects: ["Dopant non-uniformity"] }),
  P("deposition", "FE", "Deposition (thin films)", { flow: 7, legacy_ps: ["PS05"], eq: ["A09"], tech: ["cvd", "pecvd", "lpcvd", "hdpcvd", "ald", "pvd", "evaporation"], mat: ["precursor-gases", "ald-precursors", "sputter-targets"],
    description: "Addition of dielectric, semiconductor or metal films by chemical (CVD, ALD) or physical (PVD) methods.", purpose: "Build the device and interconnect layer stack.",
    inputs: ["Wafers", "Precursors / targets", "Process gases"], outputs: ["Wafers with deposited film"], parameters: ["Temperature", "Pressure", "Plasma power", "Precursor flow"], quality: ["Thickness uniformity", "Step coverage", "Film stress"], defects: ["Particles", "Voids", "Delamination"] }),
  P("cvd", "FE", "Chemical vapour deposition (CVD)", { parent: "deposition", legacy_ps: ["PS05"], eq: ["A09.01", "A09.02", "A09.03", "A09.04", "A09.05"], tech: ["cvd", "pecvd", "lpcvd", "hdpcvd"], mat: ["precursor-gases"],
    description: "Film formation from gas-phase precursors reacting at or near the wafer surface, thermally or plasma-enhanced.", purpose: "Deposit conformal dielectric and conductive films.",
    inputs: ["Precursor gases"], outputs: ["CVD film"], parameters: ["Temperature", "Pressure", "RF power (PECVD)"], quality: ["Uniformity", "Step coverage"], defects: ["Particles", "Seams"] }),
  P("ald", "FE", "Atomic layer deposition (ALD)", { parent: "deposition", legacy_ps: ["PS05"], eq: ["A09.06"], tech: ["ald"], mat: ["ald-precursors"],
    description: "Self-limiting, sequential surface reactions that deposit films one atomic layer per cycle.", purpose: "Deposit ultra-thin, highly conformal films (high-k, liners, spacers).",
    inputs: ["Alternating precursors"], outputs: ["ALD film"], parameters: ["Cycle time", "Temperature"], quality: ["Conformality", "Thickness control"], defects: ["Incomplete nucleation"] }),
  P("pvd", "FE", "Physical vapour deposition (PVD)", { parent: "deposition", legacy_ps: ["PS05", "PS11"], eq: ["A09.07", "A09.08", "A09.09"], tech: ["pvd", "evaporation"], mat: ["sputter-targets"],
    description: "Deposition of metal or compound films by sputtering a target or evaporating a source in vacuum.", purpose: "Form barrier, seed and metal layers.",
    inputs: ["Targets", "Argon"], outputs: ["Metal / barrier film"], parameters: ["Power", "Pressure", "Bias"], quality: ["Resistivity", "Coverage"], defects: ["Overhang", "Particles"] }),
  P("resist-coat", "FE", "Photoresist coat & bake", { flow: 8, legacy_ps: ["PS03"], eq: ["A02", "A03"], mat: ["photoresists", "solvents"],
    description: "Spin-coating of photoresist and associated bake steps on a coater/developer track linked to the scanner.", purpose: "Apply a uniform radiation-sensitive film for patterning.",
    inputs: ["Wafers", "Photoresist", "Adhesion promoters"], outputs: ["Resist-coated wafers"], parameters: ["Spin speed", "Bake temperature"], quality: ["Resist thickness uniformity"], defects: ["Comets", "Edge bead"] }),
  P("lithography", "FE", "Lithography (exposure)", { flow: 9, legacy_ps: ["PS02"], eq: ["A01"], tech: ["euv", "duv", "arf", "krf", "i-line", "ebeam-litho", "nil", "maskless"], mat: ["photoresists", "neon"],
    description: "Transfer of the mask (reticle) pattern into the resist by projection exposure (EUV, DUV/ArF, KrF, i-line), direct write (e-beam, laser) or nanoimprint.",
    purpose: "Define circuit patterns at the required resolution and overlay.", inputs: ["Resist-coated wafers", "Reticle"], outputs: ["Exposed wafers (latent image)"],
    parameters: ["Wavelength", "Numerical aperture", "Dose", "Focus"], quality: ["Critical dimension (CD)", "Overlay", "Throughput (wafers/hour)"], defects: ["CD variation", "Overlay error", "Stochastic defects"] }),
  P("develop", "FE", "Develop", { flow: 10, legacy_ps: ["PS03"], eq: ["A02", "A03"], mat: ["developers"], description: "Post-exposure bake and dissolution of exposed (or unexposed) resist.",
    purpose: "Reveal the resist pattern.", inputs: ["Exposed wafers", "Developer"], outputs: ["Patterned resist"], parameters: ["Develop time", "PEB temperature"], quality: ["CD uniformity"], defects: ["Scumming", "Pattern collapse"] }),
  P("etch", "FE", "Etch", { flow: 11, legacy_ps: ["PS04"], eq: ["A08"], tech: ["plasma-etch", "rie", "icp", "drie", "wet-etch"], mat: ["fluorine-gases", "chlorine-gases", "etchants"],
    description: "Selective removal of material through the resist mask, by plasma (dry) or chemical (wet) etching.", purpose: "Transfer the pattern into the underlying film or substrate.",
    inputs: ["Patterned wafers", "Etch gases / chemicals"], outputs: ["Etched features"], parameters: ["RF power", "Pressure", "Gas chemistry", "Temperature"], quality: ["Etch rate", "Selectivity", "Profile / CD", "Uniformity"], defects: ["Micro-loading", "Notching", "Residues"] }),
  P("ash-strip", "FE", "Ash / resist strip", { flow: 12, legacy_ps: ["PS07", "PS04"], eq: ["A07", "A05"], mat: ["oxygen", "strippers"], description: "Removal of residual photoresist by oxygen plasma (ashing) or wet strippers.",
    purpose: "Clear resist after etch or implant.", inputs: ["Wafers with resist"], outputs: ["Resist-free wafers"], parameters: ["Plasma power", "Temperature"], quality: ["Residue-free surface"], defects: ["Residues", "Substrate damage"] }),
  P("ion-implant", "FE", "Ion implantation", { flow: 13, legacy_ps: ["PS06"], eq: ["A10", "F04"], tech: ["ion-implantation"], mat: ["dopant-gases"],
    description: "Acceleration of dopant ions into the wafer at controlled energy and dose.", purpose: "Introduce dopants to form wells, sources/drains and junctions.",
    inputs: ["Masked wafers", "Dopant source"], outputs: ["Implanted wafers"], parameters: ["Energy", "Dose", "Tilt / twist"], quality: ["Dose uniformity", "Channelling control"], defects: ["Lattice damage", "Contamination"] }),
  P("anneal", "FE", "Annealing / RTP", { flow: 14, legacy_ps: ["PSX1"], eq: ["A12", "A13", "A14", "F05"], tech: ["rtp", "furnace-thermal", "laser-annealing"], mat: ["nitrogen"],
    description: "Thermal treatment to activate dopants and repair damage, in furnaces, rapid thermal processors or with laser (millisecond/nanosecond) annealing.",
    purpose: "Activate dopants and control diffusion within a thermal budget.", inputs: ["Implanted wafers"], outputs: ["Activated wafers"], parameters: ["Peak temperature", "Ramp rate", "Dwell time"], quality: ["Sheet resistance", "Junction depth"], defects: ["Slip", "Pattern-dependent heating"] }),
  P("cmp", "FE", "Chemical mechanical planarisation (CMP)", { flow: 15, legacy_ps: ["PS10"], eq: ["A19"], tech: ["cmp"], mat: ["cmp-slurry", "cmp-pad", "cmp-conditioner"],
    description: "Combined chemical and mechanical polishing to planarise dielectric and metal layers.", purpose: "Provide planar surfaces for subsequent lithography and remove overburden.",
    inputs: ["Wafers", "Slurry", "Pads"], outputs: ["Planarised wafers"], parameters: ["Down force", "Platen speed", "Slurry chemistry"], quality: ["Within-wafer non-uniformity", "Dishing / erosion"], defects: ["Scratches", "Dishing", "Slurry residue"] }),
  P("metallization", "FE", "Metallisation & plating", { flow: 16, legacy_ps: ["PS11"], eq: ["A17", "A18"], tech: ["electroplating", "pvd"], mat: ["plating-chemistry", "sputter-targets"],
    description: "Formation of interconnect metal, typically barrier/seed by PVD then copper electroplating (damascene).", purpose: "Build the multilevel wiring.",
    inputs: ["Patterned dielectric", "Plating chemistry"], outputs: ["Metal interconnect"], parameters: ["Current density", "Additive concentration"], quality: ["Void-free fill", "Resistivity"], defects: ["Voids", "Electromigration weak spots"] }),
  P("metrology", "FE", "Metrology", { flow: 17, legacy_ps: ["PS08"], eq: ["A25", "A26", "A27", "A28", "A29", "A30"], tech: ["cd-sem", "optical-metrology", "afm-metrology"],
    description: "Measurement of film thickness, critical dimensions, overlay and surface properties.", purpose: "Monitor and control process steps.",
    inputs: ["Wafers"], outputs: ["Measurement data for process control"], parameters: ["Precision", "Accuracy", "Throughput"], quality: ["Measurement uncertainty"], defects: [] }),
  P("inspection", "FE", "Defect inspection & review", { flow: 18, legacy_ps: ["PS09"], eq: ["A21", "A22", "A23", "A24", "A31"], tech: ["optical-inspection", "ebeam-inspection"],
    description: "Detection, classification and review of defects on patterned and unpatterned wafers (optical, e-beam).", purpose: "Find yield-limiting defects early.",
    inputs: ["Wafers"], outputs: ["Defect maps"], parameters: ["Sensitivity", "Throughput"], quality: ["Capture rate", "Nuisance rate"], defects: [] }),
  P("mask-making", "FE", "Mask / reticle making", { legacy_ps: ["PSX3"], eq: ["B"], tech: ["ebeam-litho", "maskless"], description: "Writing, inspecting, repairing and qualifying photomasks and reticles.",
    purpose: "Produce defect-free masks for lithography.", inputs: ["Mask blanks"], outputs: ["Qualified reticles"], parameters: ["Write resolution", "Placement accuracy"], quality: ["CD uniformity", "Registration"], defects: ["Mask defects", "Contamination"] }),

  // ---------- Wafer test ----------
  P("wafer-test", "TS", "Wafer probe & electrical test", { flow: 19, legacy_ps: ["PS12"], eq: ["A32", "A33"], tech: ["ate"],
    description: "Electrical testing of each die on the wafer using a prober, probe card and automated test equipment.", purpose: "Identify good dies before assembly (known-good die).",
    inputs: ["Processed wafers", "Probe cards", "Test programs"], outputs: ["Wafer maps / bin data"], parameters: ["Test time", "Parallelism", "Temperature"], quality: ["Test coverage", "Yield"], defects: ["Probe marks", "Contact failures"] }),

  // ---------- Back-end ----------
  P("wafer-thinning", "BE", "Back-grinding / wafer thinning", { flow: 20, legacy_ps: ["PSX2"], eq: ["C02", "C03", "C04", "C05"], mat: ["grinding-tape"],
    description: "Grinding and stress-relief polishing of the wafer backside to the target thickness.", purpose: "Reduce package height and enable stacking.",
    inputs: ["Probed wafers", "Back-grinding tape"], outputs: ["Thinned wafers"], parameters: ["Final thickness", "Wheel grit"], quality: ["Thickness variation", "Die strength"], defects: ["Cracks", "Warpage"] }),
  P("wafer-mount", "BE", "Wafer mounting", { legacy_ps: ["PS13"], eq: ["C06", "C07"], mat: ["dicing-tape"], description: "Laminating the wafer onto dicing tape on a frame.",
    purpose: "Hold dies in place during and after dicing.", inputs: ["Thinned wafers", "Dicing tape", "Frames"], outputs: ["Framed wafers"], parameters: ["Lamination temperature"], quality: ["Void-free mounting"], defects: ["Air bubbles"] }),
  P("dicing", "BE", "Dicing", { flow: 21, legacy_ps: ["PS13"], eq: ["C01", "E10", "F07"], tech: ["blade-dicing", "laser-dicing", "stealth-dicing", "plasma-dicing", "dbg", "laser-grooving"], mat: ["silicon", "sic", "gan", "gaas", "glass"],
    description: "Separation of the wafer into individual dies by blade sawing, laser ablation, stealth (internal) laser modification or plasma etching.", purpose: "Singulate dies with minimal chipping and kerf.",
    inputs: ["Mounted wafers"], outputs: ["Singulated dies on tape"], parameters: ["Kerf width", "Feed speed", "Laser wavelength / pulse (laser dicing)"], quality: ["Chipping", "Die strength", "Throughput"], defects: ["Chipping", "Cracks", "Debris"] }),
  P("die-attach", "BE", "Die attach", { flow: 22, legacy_ps: ["PS15"], eq: ["C08", "C09", "C10", "E11"], tech: ["die-bonding"], mat: ["die-attach-materials", "leadframes", "substrates"],
    description: "Pick-and-place of dies onto a leadframe or substrate using adhesive, solder or sinter materials.", purpose: "Mechanically and thermally attach the die.",
    inputs: ["Singulated dies", "Leadframes / substrates", "Die-attach material"], outputs: ["Attached dies"], parameters: ["Placement accuracy", "Bond force", "Cure profile"], quality: ["Placement accuracy", "Void content"], defects: ["Voids", "Die tilt"] }),
  P("wire-bond", "BE", "Wire bonding", { flow: 23, legacy_ps: ["PS15"], eq: ["C12", "C13", "C14", "C15", "E12"], tech: ["wire-bonding"], mat: ["bonding-wire"],
    description: "Connection of die pads to package leads with fine gold, copper or aluminium wire (ball or wedge bonding).", purpose: "Provide electrical interconnect.",
    inputs: ["Attached dies", "Bond wire"], outputs: ["Wire-bonded assemblies"], parameters: ["Ultrasonic power", "Bond force", "Temperature"], quality: ["Pull / shear strength"], defects: ["Non-stick", "Wire sweep"] }),
  P("flip-chip", "BE", "Flip-chip bonding", { legacy_ps: ["PS15"], eq: ["C11", "E13", "C16", "C19"], tech: ["flip-chip", "tcb"], mat: ["solder", "underfill", "substrates"],
    description: "Face-down attachment of bumped dies to a substrate by mass reflow or thermo-compression bonding.", purpose: "Area-array interconnect with short electrical paths.",
    inputs: ["Bumped dies", "Substrates"], outputs: ["Flip-chip assemblies"], parameters: ["Bond force", "Temperature profile", "Alignment accuracy"], quality: ["Joint yield", "Alignment"], defects: ["Non-wet", "Bridging", "Cracks"] }),
  P("molding", "BE", "Molding / encapsulation", { flow: 24, legacy_ps: ["PS14"], eq: ["C20", "C21", "C22", "C23", "C24", "C25", "E14"], tech: ["compression-molding"], mat: ["molding-compound", "underfill"],
    description: "Encapsulation of assemblies with epoxy molding compound (transfer or compression molding) and dispensing of underfill.", purpose: "Protect the die and interconnect.",
    inputs: ["Assemblies", "Molding compound"], outputs: ["Molded strips / panels"], parameters: ["Mold temperature", "Pressure", "Cure time"], quality: ["Void-free fill", "Warpage"], defects: ["Voids", "Wire sweep", "Incomplete fill"] }),
  P("plating-be", "BE", "Lead plating & finishing", { legacy_ps: ["PS14"], eq: [], mat: ["plating-chemistry"], description: "Plating of external leads for solderability.",
    purpose: "Ensure board-level solderability.", inputs: ["Molded packages"], outputs: ["Plated leads"], parameters: ["Plating thickness"], quality: ["Solderability"], defects: ["Whiskers"] }),
  P("marking", "BE", "Marking", { flow: 25, legacy_ps: ["PS14"], eq: ["C26", "C27", "E09"], tech: ["laser-marking"], description: "Laser (or ink) marking of packages, strips or wafers with identifiers.",
    purpose: "Provide traceability and product identification.", inputs: ["Packages / wafers"], outputs: ["Marked units"], parameters: ["Laser wavelength", "Mark depth", "Contrast"], quality: ["Readability", "Mark depth"], defects: ["Burn-through", "Low contrast"] }),
  P("singulation", "BE", "Package singulation", { legacy_ps: ["PS14"], eq: ["C32", "C29", "C30"], tech: ["laser-cutting", "blade-dicing"], description: "Sawing, punching or laser cutting of molded strips into individual packages.",
    purpose: "Separate finished packages.", inputs: ["Molded strips"], outputs: ["Individual packages"], parameters: ["Cut speed", "Kerf"], quality: ["Dimensional accuracy", "Burr"], defects: ["Burr", "Delamination"] }),
  P("package-inspection", "BE", "Package inspection", { flow: 26, legacy_ps: ["PS16"], eq: ["C34", "C35", "C36", "E06"], tech: ["optical-inspection", "xray-inspection"],
    description: "Automated optical and X-ray inspection of packages for mechanical and internal defects.", purpose: "Screen out assembly defects.",
    inputs: ["Packages"], outputs: ["Inspection results"], parameters: ["Resolution", "Throughput"], quality: ["Escape rate"], defects: [] }),
  P("final-test", "BE", "Final / package test", { flow: 27, legacy_ps: ["PS16"], eq: ["C37", "C39", "C40", "C41", "C42", "E02", "E07", "E08"], tech: ["ate"],
    description: "Electrical test of packaged devices with ATE and handlers, across temperature where required.", purpose: "Guarantee shipped-product quality and bin by performance.",
    inputs: ["Packaged devices", "Test programs"], outputs: ["Tested, binned devices"], parameters: ["Test time", "Parallelism", "Temperature"], quality: ["Test coverage", "Yield"], defects: ["Contact failures"] }),
  P("burn-in", "BE", "Burn-in & reliability", { legacy_ps: ["PS16"], eq: ["C38", "E04", "E05"], tech: ["burn-in"], description: "Stressing devices at elevated voltage and temperature to screen early-life failures.",
    purpose: "Remove infant-mortality failures.", inputs: ["Tested devices"], outputs: ["Screened devices"], parameters: ["Temperature", "Voltage", "Duration"], quality: ["Early failure rate"], defects: [] }),

  // ---------- Advanced packaging ----------
  P("tsv", "AP", "Through-silicon via (TSV)", { flow: null, legacy_ps: ["PSX5"], eq: ["D13", "A08.05", "A18"], tech: ["tsv", "drie", "electroplating"], description: "Vertical vias etched through silicon, lined, filled with metal and revealed from the backside.",
    purpose: "Vertical interconnect for 3D stacks and interposers.", inputs: ["Device wafers"], outputs: ["Wafers with TSVs"], parameters: ["Via aspect ratio"], quality: ["Void-free fill"], defects: ["Voids", "Cu pumping"] }),
  P("tgv", "AP", "Through-glass via (TGV) & glass core", { legacy_ps: ["PSX5"], eq: ["D14", "D18", "C28"], tech: ["tgv", "laser-drilling"], mat: ["glass"], description: "Formation of vias in glass substrates or interposers, commonly by laser modification followed by wet etching, or by laser drilling.",
    purpose: "Enable glass-core substrates and glass interposers.", inputs: ["Glass panels / wafers"], outputs: ["Via-patterned glass"], parameters: ["Via diameter", "Taper"], quality: ["Via geometry", "Crack-free glass"], defects: ["Micro-cracks"] }),
  P("rdl", "AP", "Redistribution layer (RDL)", { legacy_ps: ["PSX5"], eq: ["D15", "A18", "A01.05", "A01.08"], tech: ["rdl"], description: "Thin-film wiring layers (polymer dielectric + plated copper) that re-route die I/O.",
    purpose: "Fan in/out interconnect at wafer or panel level.", inputs: ["Wafers / reconstituted panels"], outputs: ["RDL layers"], parameters: ["Line/space"], quality: ["Line/space", "Via yield"], defects: ["Opens", "Shorts"] }),
  P("wlp", "AP", "Wafer-level packaging (fan-in)", { legacy_ps: ["PSX5"], eq: ["D08", "D20", "A18", "A01.05"], tech: ["wlp"], description: "Packaging performed on the whole wafer before singulation, with I/O within the die footprint.",
    purpose: "Chip-scale packages with minimal footprint.", inputs: ["Device wafers"], outputs: ["WLCSP"], parameters: [], quality: [], defects: [] }),
  P("fan-out", "AP", "Fan-out wafer/panel-level packaging", { legacy_ps: ["PSX5"], eq: ["D05", "D06", "D07", "D10", "C20", "A18", "A01.05", "A01.08"], tech: ["fan-out", "panel-level"], description: "Dies embedded in a reconstituted wafer or panel with RDL extending beyond the die edge.",
    purpose: "Higher I/O density without a substrate.", inputs: ["Known-good dies", "Carrier", "Mold compound"], outputs: ["Fan-out packages"], parameters: ["Die shift", "Warpage"], quality: ["Die placement accuracy"], defects: ["Die shift", "Warpage"] }),
  P("interposer-25d", "AP", "2.5D integration (interposer)", { legacy_ps: ["PSX5"], eq: ["D01", "D09", "D11", "D16", "D17", "D18"], tech: ["interposer-25d"], mat: ["silicon", "glass", "substrates"],
    description: "Side-by-side placement of dies on a silicon, organic or glass interposer or bridge.", purpose: "High-bandwidth die-to-die connectivity (e.g. logic + HBM).",
    inputs: ["Dies", "Interposer"], outputs: ["2.5D module"], parameters: ["Microbump pitch"], quality: ["Interconnect yield", "Warpage"], defects: ["Bump cracks"] }),
  P("3d-stacking", "AP", "3D stacking & HBM", { legacy_ps: ["PSX5"], eq: ["D02", "D03", "D21", "D22", "D23", "C16", "C17"], tech: ["3d-ic", "hbm", "tcb", "hybrid-bonding"],
    description: "Vertical stacking of dies (e.g. DRAM stacks for HBM) connected by TSVs and microbumps or direct/hybrid bonds.", purpose: "Increase bandwidth and density per footprint.",
    inputs: ["Thinned dies with TSVs"], outputs: ["Die stacks"], parameters: ["Bond force/temperature", "Alignment"], quality: ["Stack yield", "Thermal resistance"], defects: ["Misalignment", "Voids"] }),
  P("chiplet", "AP", "Chiplet integration", { legacy_ps: ["PSX5"], eq: ["D04", "C11", "C16", "C17"], tech: ["chiplet"], description: "Assembly of multiple smaller dies (chiplets) into one package via 2.5D/3D or advanced substrates.",
    purpose: "Heterogeneous integration and yield improvement.", inputs: ["Chiplets"], outputs: ["Multi-die package"], parameters: [], quality: [], defects: [] }),
  P("hybrid-bond", "AP", "Hybrid / direct bonding", { legacy_ps: ["PSX5", "PS15"], eq: ["C17", "D12", "C18"], tech: ["hybrid-bonding", "wafer-bonding"], description: "Bonding of dies or wafers through direct dielectric-dielectric and Cu-Cu contact without solder.",
    purpose: "Sub-10 µm pitch interconnect for 3D integration.", inputs: ["Planarised, activated surfaces"], outputs: ["Bonded stacks"], parameters: ["Surface roughness", "Alignment accuracy", "Anneal temperature"], quality: ["Bond strength", "Void density"], defects: ["Voids", "Particles", "Misalignment"] }),
  P("temp-bond-debond", "AP", "Temporary bond / debond", { legacy_ps: ["PSX5"], eq: ["C18"], tech: ["wafer-bonding", "laser-debonding"], description: "Temporary attachment of thin wafers to carriers and later release (e.g. by laser debonding).",
    purpose: "Handle thin wafers through backside processing.", inputs: ["Device wafer", "Carrier", "Adhesive"], outputs: ["Released thin wafer"], parameters: ["Debond energy"], quality: ["Residue-free release"], defects: ["Cracks", "Residue"] }),
  P("advanced-substrate", "AP", "Advanced substrate & panel processing", { legacy_ps: ["PSX5"], eq: ["D19", "C28", "D14"], tech: ["panel-level", "laser-drilling"], mat: ["substrates", "abf", "glass"],
    description: "Build-up substrate and panel-level processes: via drilling, lithography and plating on large-format panels.", purpose: "High-density substrates for large packages.",
    inputs: ["Core panels", "Build-up film"], outputs: ["Package substrates"], parameters: ["Via diameter", "Line/space"], quality: ["Layer registration"], defects: ["Via defects", "Warpage"] }),

  // ---------- Display ----------
  P("laser-lift-off", "DS", "Laser lift-off", { legacy_ps: ["PSX6"], eq: ["I06"], tech: ["laser-lift-off", "excimer"], description: "Separation of a film or device layer from a transparent carrier by laser absorption at the interface.",
    purpose: "Release flexible displays or MicroLEDs from growth/carrier substrates.", inputs: ["Layer on carrier"], outputs: ["Released layer"], parameters: ["Wavelength", "Fluence"], quality: ["Release yield"], defects: ["Cracks", "Residue"] }),
  P("ltps-anneal", "DS", "Laser annealing (LTPS / display)", { legacy_ps: ["PSX6"], eq: ["I07"], tech: ["laser-annealing", "excimer"], description: "Laser crystallisation of amorphous silicon into polysilicon for display backplanes.",
    purpose: "High-mobility thin-film transistors.", inputs: ["a-Si coated glass"], outputs: ["Poly-Si backplane"], parameters: ["Fluence", "Overlap"], quality: ["Mura / uniformity"], defects: ["Mura"] }),
  P("mass-transfer", "DS", "MicroLED mass transfer & repair", { legacy_ps: ["PSX6"], eq: ["I08", "I09", "I05", "I10"], tech: ["laser-repair"], description: "Transfer of large numbers of MicroLED dies to the backplane and repair of defective pixels.",
    purpose: "Assemble MicroLED displays.", inputs: ["MicroLED dies", "Backplane"], outputs: ["Populated backplane"], parameters: ["Transfer yield", "Placement accuracy"], quality: ["Pixel yield"], defects: ["Missing pixels"] }),

  // ---------- Fab infrastructure / subfab ----------
  P("amhs", "FA", "Automated material handling", { legacy_ps: ["PSX4"], eq: ["J01", "J02", "J03", "J04", "J05", "J07", "A34", "A35", "A36"], description: "Overhead hoist transport, stockers and vehicles that move FOUPs between tools.",
    purpose: "Deliver wafers to tools without manual handling.", inputs: ["FOUPs"], outputs: ["Delivered lots"], parameters: ["Moves per hour"], quality: ["Delivery time"], defects: [] }),
  P("equipment-automation", "FA", "Tool automation & wafer handling", { legacy_ps: ["PSX4"], eq: ["A37", "A38", "A39", "A40", "J06", "J08", "J09", "J10", "J11", "J12", "J13", "J14", "J15"], description: "EFEMs, wafer robots, load ports and factory software linking tools to the fab.",
    purpose: "Automated, contamination-free wafer transfer and tool control.", inputs: ["FOUPs"], outputs: ["Wafers at process chamber"], parameters: ["Transfer time", "Placement repeatability"], quality: ["Particle adders"], defects: [] }),
  P("vacuum-abatement", "FA", "Vacuum & abatement (subfab)", { legacy_ps: ["PSX4"], eq: ["A41", "A42", "A45", "L01", "L02", "L06"], mat: ["nitrogen"], description: "Dry, turbo and cryo pumps creating process vacuum, and abatement systems that treat process exhaust.",
    purpose: "Maintain process vacuum and destroy hazardous or greenhouse exhaust gases.", inputs: ["Process exhaust"], outputs: ["Treated exhaust"], parameters: ["Pumping speed", "Destruction efficiency"], quality: ["Uptime"], defects: [] }),
  P("gas-chemical-delivery", "FA", "Gas & chemical delivery", { legacy_ps: ["PSX4"], eq: ["A43", "A44", "L04", "L05"], mat: ["nitrogen", "argon", "hydrogen", "fluorine-gases", "chlorine-gases", "acids"],
    description: "Gas cabinets, valve manifold boxes, bulk gas and chemical distribution that feed tools.", purpose: "Deliver pure, controlled process fluids safely.",
    inputs: ["Bulk / specialty gases and chemicals"], outputs: ["Point-of-use supply"], parameters: ["Purity", "Pressure / flow stability"], quality: ["Purity at point of use"], defects: [] }),
  P("utilities", "FA", "Utilities (UPW, CDA, cooling, power)", { legacy_ps: ["PSX4"], eq: ["L03", "L07", "L08", "L09", "L10", "L11", "L12"], mat: ["ultrapure-water"], description: "Ultrapure water, clean dry air, process cooling, waste treatment, power distribution and facility monitoring.",
    purpose: "Provide the utilities every tool depends on.", inputs: ["City water", "Power", "Air"], outputs: ["UPW", "CDA", "Cooling water", "Conditioned power"], parameters: ["Resistivity (UPW)", "Dew point (CDA)"], quality: ["Utility uptime"], defects: [] }),
];
