// Subsystem and component-class reference (editorial engineering reference).
// Supplier links are NOT editorial: they come from the Batch-1 supplier register (source-backed
// capability or documented supply) via the legacy BOM codes listed in `bom`.
// typical_in: taxonomy codes (prefix) of equipment that generically contains the subsystem;
// laser:true adds every laser-relevant taxonomy node. These are generic architecture patterns.

const S = (slug, name, o) => ({ slug, name, ...o });
export const SUBSYSTEMS = [
  S("laser", "Laser subsystem", { laser: true, typical_in: ["A01.01", "A01.02", "A01.03", "A01.04"],
    architecture: "Laser source (fiber, DPSS, ultrafast, excimer or CO₂) with power supply, cooling and beam delivery; in lithography an excimer or EUV light source.",
    functions: ["Generate photons at the required wavelength, pulse duration and power"], inputs: ["Electrical power", "Cooling water", "Trigger / control signals"], outputs: ["Laser beam"],
    parameters: ["Wavelength", "Pulse duration", "Pulse energy", "Average power", "Repetition rate", "Beam quality (M²)"], failure_modes: ["Power drift", "Pump diode degradation", "Optics contamination"],
    interfaces: ["Trigger/sync to motion & scanner", "Cooling loop", "Interlock chain"], integration: ["Thermal stability", "Beam pointing stability", "Laser safety class"], cost_drivers: ["Source type and power class"] }),
  S("optics", "Optical & beam-delivery subsystem", { laser: true, typical_in: ["A01", "A21", "A22", "A23", "B"],
    architecture: "Beam expanders, mirrors, scanners (galvo), f-theta or projection lenses, beam shapers/DOEs and modulators.",
    functions: ["Shape, steer and focus the beam or image the pattern"], inputs: ["Laser beam / illumination"], outputs: ["Focused spot or projected image"],
    parameters: ["Spot size", "Field size", "Numerical aperture", "Transmission", "Scan speed"], failure_modes: ["Contamination", "Thermal lensing", "Misalignment"],
    interfaces: ["Laser", "Motion", "Autofocus"], integration: ["Optical alignment", "Purging"], cost_drivers: ["Lens complexity", "Wavelength (UV optics)"] }),
  S("motion", "Motion subsystem", { laser: true, typical_in: ["A01", "A33", "C01", "C10", "C11", "C12", "C16", "C17", "C19", "B07", "B08"],
    architecture: "Linear/rotary stages (mechanical or air-bearing) with linear or servo motors, encoders or interferometers and a motion controller.",
    functions: ["Position wafer or head with required accuracy and speed"], inputs: ["Motion commands", "Power"], outputs: ["Positioned substrate / tool"],
    parameters: ["Travel", "Accuracy", "Repeatability", "Velocity / acceleration", "Settling time"], failure_modes: ["Encoder error", "Thermal drift", "Bearing wear"],
    interfaces: ["Motion controller", "Laser trigger (PSO)", "Vision"], integration: ["Vibration isolation", "Thermal management"], cost_drivers: ["Accuracy class", "Air bearings", "Metrology frame"] }),
  S("vacuum", "Vacuum subsystem", { typical_in: ["A01.01", "A08", "A09", "A10", "A24", "A26", "A39", "A41", "A42", "C17", "C18", "B07"],
    architecture: "Process chamber, load locks, dry/turbo/cryo pumps, valves, gauges and pressure control.",
    functions: ["Create and control process vacuum"], inputs: ["Power", "Purge N₂", "Cooling"], outputs: ["Controlled chamber pressure"],
    parameters: ["Base pressure", "Pump-down time", "Leak rate", "Pressure control accuracy"], failure_modes: ["Leaks", "Pump failure", "Deposit build-up"],
    interfaces: ["Subfab pumps & abatement", "Gas delivery", "Controller"], integration: ["Chamber matching", "Exhaust routing"], cost_drivers: ["Pump class", "Chamber material"] }),
  S("rf", "RF / plasma subsystem", { typical_in: ["A08", "A09.02", "A09.04", "A09.06", "A09.07", "A09.08", "A07", "C01.04"],
    architecture: "RF generators, matching networks, electrodes/coils, electrostatic chuck and plasma sensors (e.g. OES).",
    functions: ["Generate and sustain plasma with controlled density and ion energy"], inputs: ["AC power", "Process gases"], outputs: ["Plasma"],
    parameters: ["RF frequency", "RF power", "Reflected power", "Pulsing"], failure_modes: ["Arcing", "Match drift", "Electrode erosion"],
    interfaces: ["Chamber", "Controller", "Endpoint detection"], integration: ["RF grounding & shielding", "Chamber matching"], cost_drivers: ["Frequency bands", "Power level"] }),
  S("gas", "Gas delivery subsystem", { typical_in: ["A08", "A09", "A10", "A11", "A12", "A16", "A43", "G"],
    architecture: "Gas panel with mass-flow controllers, valves, regulators, filters, purifiers; fed from gas cabinets/VMBs.",
    functions: ["Deliver precise process gas mixtures"], inputs: ["Facility gases"], outputs: ["Controlled gas flow"],
    parameters: ["Flow accuracy", "Response time", "Leak integrity", "Purity"], failure_modes: ["MFC drift", "Valve leakage", "Contamination"],
    interfaces: ["Facility gas", "Chamber", "Controller", "Toxic gas monitoring"], integration: ["Weld quality", "Safety interlocks"], cost_drivers: ["Number of lines", "Hazardous gas handling"] }),
  S("chemical", "Chemical delivery subsystem", { typical_in: ["A02", "A03", "A04", "A05", "A18", "A19", "A44", "C25"],
    architecture: "Chemical supply modules, pumps, filters, heaters, dispense nozzles and recirculation.",
    functions: ["Deliver and recirculate liquid chemistries"], inputs: ["Bulk chemicals", "UPW"], outputs: ["Controlled dispense"],
    parameters: ["Flow", "Temperature", "Concentration", "Particle count"], failure_modes: ["Filter clogging", "Pump failure", "Concentration drift"],
    interfaces: ["Facility chemical distribution", "Drain / exhaust"], integration: ["Material compatibility"], cost_drivers: ["Chemistry count", "Materials (PFA)"] }),
  S("wafer-handling", "Wafer-handling subsystem", { laser: true, typical_in: ["A", "B", "C01", "C04", "C06", "C17", "C18", "J"],
    architecture: "Load ports, EFEM, atmospheric/vacuum robots, aligners, FOUP interfaces.",
    functions: ["Transfer wafers between carrier and process modules"], inputs: ["FOUPs / cassettes / frames"], outputs: ["Wafers at process position"],
    parameters: ["Throughput", "Placement repeatability", "Particle adders"], failure_modes: ["Mis-picks", "Wafer breakage", "Robot calibration drift"],
    interfaces: ["SEMI E84/E87 load-port standards", "Tool controller"], integration: ["Mini-environment cleanliness"], cost_drivers: ["Robot count", "Vacuum handling"] }),
  S("vision", "Vision & alignment subsystem", { laser: true, typical_in: ["A21", "A22", "A23", "C01", "C10", "C11", "C12", "C16", "C17", "C26", "C36"],
    architecture: "Cameras, illumination, lenses, vision controllers, ID readers, autofocus/height sensors.",
    functions: ["Align, recognise, inspect and read IDs"], inputs: ["Images"], outputs: ["Positions / measurements / pass-fail"],
    parameters: ["Resolution", "Frame rate", "Alignment accuracy"], failure_modes: ["Recognition errors", "Illumination drift"],
    interfaces: ["Motion controller", "Tool software"], integration: ["Calibration"], cost_drivers: ["Sensor and optics grade"] }),
  S("metrology", "Metrology subsystem", { typical_in: ["A25", "A26", "A27", "A28", "A29", "A30", "B09"],
    architecture: "Measurement heads (optical, e-beam, X-ray, AFM) with reference standards and analysis software.",
    functions: ["Measure dimensions, films and overlay"], inputs: ["Wafers"], outputs: ["Measurements"], parameters: ["Precision", "Accuracy", "TMU"], failure_modes: ["Calibration drift"],
    interfaces: ["Fab APC / host"], integration: ["Tool matching"], cost_drivers: ["Measurement physics"] }),
  S("cooling", "Cooling subsystem", { laser: true, typical_in: ["A01", "A08", "A09", "A10", "A14"],
    architecture: "Chillers, heat exchangers, cooling loops for sources, chucks and electronics.",
    functions: ["Remove heat and stabilise temperatures"], inputs: ["Facility cooling water", "Power"], outputs: ["Temperature-controlled coolant"],
    parameters: ["Cooling capacity", "Temperature stability"], failure_modes: ["Flow loss", "Leaks"], interfaces: ["Laser / chuck / electronics"], integration: ["Facility water quality"], cost_drivers: ["Capacity and stability"] }),
  S("thermal", "Thermal subsystem", { typical_in: ["A11", "A12", "A13", "A16", "C16", "C20", "C38"],
    architecture: "Heaters, lamps, heated chucks, thermocouples/RTDs and temperature controllers.",
    functions: ["Heat substrates to controlled profiles"], inputs: ["Power"], outputs: ["Controlled temperature"], parameters: ["Ramp rate", "Uniformity", "Peak temperature"],
    failure_modes: ["Heater failure", "Sensor drift"], interfaces: ["Controller"], integration: ["Thermal budget"], cost_drivers: ["Uniformity requirement"] }),
  S("electrical", "Electrical & power subsystem", { laser: true, typical_in: ["A", "B", "C", "D", "J"],
    architecture: "Power distribution, SMPS, UPS, transformers, contactors, protection, cabling and connectors.",
    functions: ["Distribute conditioned power safely"], inputs: ["Facility power"], outputs: ["Tool power rails"], parameters: ["Power rating", "Power quality"],
    failure_modes: ["Voltage sags", "Component failure"], interfaces: ["Facility electrical"], integration: ["SEMI S2 electrical safety", "EMC"], cost_drivers: ["Power rating"] }),
  S("control", "Control & automation subsystem", { laser: true, typical_in: ["A", "B", "C", "D", "J"],
    architecture: "Industrial PCs, PLCs, motion controllers, I/O and fieldbus networks.",
    functions: ["Sequence the tool and coordinate subsystems"], inputs: ["Recipes", "Sensor data"], outputs: ["Actuator commands", "Data logs"], parameters: ["Cycle determinism", "I/O count"],
    failure_modes: ["Controller faults", "Communication loss"], interfaces: ["SECS/GEM host interface", "Fieldbuses"], integration: ["Software architecture"], cost_drivers: ["Controller platform"] }),
  S("safety", "Safety subsystem", { laser: true, typical_in: ["A", "B", "C", "D"],
    architecture: "Safety PLC/relays, interlocks, EMO, enclosures, laser safety, gas detection and fume extraction.",
    functions: ["Protect people and equipment"], inputs: ["Interlock and sensor signals"], outputs: ["Safe-state commands"], parameters: ["Safety integrity level", "Response time"],
    failure_modes: ["Interlock bypass", "Sensor failure"], interfaces: ["All subsystems", "Facility alarms"], integration: ["SEMI S2 / S8 compliance", "Laser class enclosures"], cost_drivers: ["Hazard class"] }),
  S("software", "Software subsystem", { laser: true, typical_in: ["A", "B", "C", "D", "J"],
    architecture: "Tool control software, recipe management, GUI, data collection and host communication.",
    functions: ["Operate, log and integrate the tool with the factory"], inputs: ["Operator / host commands"], outputs: ["Tool actions", "Reports"], parameters: ["Recipe capacity", "Data rates"],
    failure_modes: ["Bugs", "Integration faults"], interfaces: ["SECS/GEM, GEM300, EDA/Interface A"], integration: ["Fab host integration"], cost_drivers: ["Development effort"] }),
];

// Component classes. `bom` = legacy Batch-1 BOM codes (laser-dicing reference BOM + lithography/RF extras).
const C = (slug, cat, name, subsystem, bom = []) => ({ slug, cat, name, subsystem, bom });
export const COMPONENTS = [
  // Motion
  C("servo-motor", "Motion", "Servo motor", "motion", ["BOM14"]), C("servo-drive", "Motion", "Servo drive / motion controller", "motion", ["BOM13"]),
  C("linear-motor", "Motion", "Linear motor", "motion", ["BOM04"]), C("linear-stage", "Motion", "Linear / air-bearing stage", "motion", ["BOM03"]),
  C("ball-screw", "Motion", "Ball screw", "motion"), C("encoder", "Motion", "Encoder / interferometer", "motion", ["BOM05"]), C("bearing", "Motion", "Bearing / guide rail", "motion"),
  C("actuator", "Motion", "Actuator", "motion"), C("piezo-actuator", "Motion", "Piezo actuator", "motion"),
  // Optical
  C("laser-source", "Optical", "Laser source", "laser", ["BOM01"]), C("light-source-litho", "Optical", "Lithography light source", "laser", ["LIGHT_SOURCE"]),
  C("beam-expander", "Optical", "Beam expander", "optics", ["BOM07"]), C("mirror", "Optical", "Mirror", "optics"), C("lens", "Optical", "Lens / projection optics", "optics", ["OPTICS"]),
  C("f-theta-lens", "Optical", "F-theta lens", "optics", ["BOM06"]), C("galvo-scanner", "Optical", "Galvo scanner / scan head", "optics", ["BOM02"]),
  C("beam-shaper", "Optical", "Beam shaper / DOE", "optics", ["BOM20"]), C("aom", "Optical", "Acousto-optic modulator (AOM)", "optics", ["BOM08"]),
  C("isolator", "Optical", "Optical isolator", "optics"), C("fiber", "Optical", "Optical fiber / beam delivery", "optics"), C("photodetector", "Optical", "Photodiode / optical detector", "optics"),
  C("camera", "Optical", "Camera / ID reader", "vision", ["BOM09"]), C("imaging-system", "Optical", "Imaging system", "vision"),
  C("autofocus", "Optical", "Autofocus / height sensor", "vision", ["BOM21"]),
  // Vacuum
  C("dry-pump", "Vacuum", "Dry pump", "vacuum", ["BOM15"]), C("turbo-pump", "Vacuum", "Turbo-molecular pump", "vacuum"), C("cryo-pump", "Vacuum", "Cryo pump", "vacuum"),
  C("vacuum-gauge", "Vacuum", "Vacuum gauge", "vacuum"), C("vacuum-valve", "Vacuum", "Vacuum valve", "vacuum"), C("pressure-controller", "Vacuum", "Pressure / vacuum controller", "vacuum"),
  // Plasma / RF
  C("rf-generator", "Plasma / RF", "RF generator", "rf", ["SUB-RF"]), C("rf-match", "Plasma / RF", "RF match network", "rf"), C("electrode", "Plasma / RF", "Electrode / showerhead", "rf"),
  C("esc", "Plasma / RF", "Electrostatic chuck (ESC)", "rf"), C("oes", "Plasma / RF", "Plasma sensor / OES", "rf"),
  // Thermal
  C("heater", "Thermal", "Heater / lamp", "thermal"), C("thermocouple", "Thermal", "Thermocouple / RTD", "thermal"), C("chiller", "Thermal", "Chiller", "cooling", ["BOM16"]),
  C("temp-controller", "Thermal", "Temperature controller", "thermal"),
  // Gas / chemical
  C("mfc", "Gas / chemical", "Mass-flow controller (MFC)", "gas"), C("gas-cabinet", "Gas / chemical", "Gas cabinet / VMB", "gas"), C("gas-valve", "Gas / chemical", "Process valve / regulator", "gas"),
  C("gas-purifier", "Gas / chemical", "Gas purifier / filter", "gas"), C("chemical-pump", "Gas / chemical", "Chemical pump", "chemical"), C("chemical-delivery", "Gas / chemical", "Chemical delivery system", "chemical"),
  C("fume-extraction", "Gas / chemical", "Fume extraction", "safety", ["BOM17"]),
  // Automation
  C("plc", "Automation", "PLC", "control", ["BOM11"]), C("ipc", "Automation", "Industrial PC", "control", ["BOM12"]), C("hmi", "Automation", "HMI", "control"),
  C("wafer-robot", "Automation", "Wafer robot / EFEM", "wafer-handling", ["BOM22"]), C("vision-controller", "Automation", "Vision controller", "vision", ["BOM10"]),
  C("motion-controller", "Automation", "Motion controller", "motion"), C("safety-plc", "Automation", "Safety PLC / safety system", "safety", ["BOM18"]),
  C("network-module", "Automation", "Industrial network module", "control"), C("tool-software", "Automation", "Tool / scan-control software", "software", ["BOM19"]),
  // Electrical
  C("power-supply", "Electrical", "Power supply / SMPS", "electrical"), C("ups", "Electrical", "UPS", "electrical"), C("transformer", "Electrical", "Transformer", "electrical"),
  C("contactor-relay", "Electrical", "Contactor / relay", "electrical"), C("circuit-protection", "Electrical", "Circuit protection", "electrical"), C("cable-connector", "Electrical", "Cable / connector", "electrical"),
];
