// Search synonym groups. Each group is treated as equivalent at query time.
// Abbreviations are expanded only where the expansion is unambiguous in a semiconductor-equipment context.
export const SYNONYMS = [
  ["semiconductor equipment", "semicon equipment", "chip manufacturing equipment", "wafer fab equipment", "wfe"],
  ["etch", "etching", "etcher"],
  ["cvd", "chemical vapor deposition", "chemical vapour deposition"],
  ["pecvd", "plasma enhanced cvd", "plasma-enhanced chemical vapor deposition"],
  ["pvd", "physical vapor deposition", "physical vapour deposition", "sputtering", "sputter"],
  ["ald", "atomic layer deposition"],
  ["ate", "automated test equipment", "tester"],
  ["cmp", "chemical mechanical planarization", "chemical mechanical polishing", "chemical mechanical planarisation"],
  ["euv", "extreme ultraviolet"],
  ["duv", "deep ultraviolet"],
  ["dicing", "wafer dicing"],
  ["stealth dicing", "sd engine"],
  ["die attach", "die bonding", "die bonder"],
  ["tcb", "thermo compression bonding", "thermocompression bonding", "tc bonding", "tc bonder"],
  ["hybrid bonding", "direct bonding", "cu-cu bonding"],
  ["hbm", "high bandwidth memory"],
  ["fowlp", "fan-out wafer level packaging", "fan out", "fan-out"],
  ["wlp", "wafer level packaging", "wafer-level packaging"],
  ["osat", "outsourced semiconductor assembly and test"],
  ["atmp", "assembly test marking packaging"],
  ["amhs", "automated material handling", "oht", "overhead hoist transport"],
  ["efem", "equipment front end module"],
  ["mfc", "mass flow controller"],
  ["rf", "radio frequency"],
  ["llo", "laser lift-off", "laser lift off"],
  ["metrology", "measurement"],
  ["inspection", "defect inspection"],
  ["litho", "lithography"],
  ["implant", "ion implantation", "implanter"],
  ["anneal", "annealing"],
  ["galvo", "galvanometer scanner", "scan head"],
  ["ultrafast", "ultrashort pulse", "usp"],
  ["tgv", "through glass via", "glass core"],
  ["tsv", "through silicon via"],
];
